### ISSUE TITLE
The `api-gw/intentions.yaml` file is missing from main branch

### ISSUE THREAD

**Issue by lxdlam** [hashicorp-education/learn-consul-get-started-kubernetes#6]
This file is mentioned in the [third step](https://developer.hashicorp.com/consul/tutorials/get-started-kubernetes/kubernetes-gs-ingress) of the tutorial, in [Deploy Consul API Gateway](https://developer.hashicorp.com/consul/tutorials/get-started-kubernetes/kubernetes-gs-ingress) section. 

I also encountered issues when install the Consul Gateway API CRDs, which is unmentioned in the doc site.

Is this repository considered deprecated or only match with specific consul version?

**Comment by im2nguyen** [comment]
Hello! sorry for the late response, which variant are you running? (hcp or self-managed, and which cloud provider -- aws, azure or local)?

**Comment by im2nguyen** [comment]
we're experiencing some problems with self-managed local since we need to set up metallb for apigw to work, but the other variants should work if you pull from `main`

**Comment by lxdlam** [comment]
> we're experiencing some problems with self-managed local since we need to set up metallb for apigw to work, but the other variants should work if you pull from `main`

Exactly self-managed local. I'm experimenting it locally to test if we can adopt the consul in our already built k8s cluster smoothly.

**Comment by p81061473525** [comment]
I get the same thing . 
```
> k describe Gateway/api-gateway --namespace consul
Name:         api-gateway
Namespace:    consul
Labels:       <none>
Annotations:  <none>
API Version:  gateway.networking.k8s.io/v1beta1
Kind:         Gateway
Metadata:
  Creation Timestamp:  2023-12-09T13:12:33Z
  Generation:          1
  Resource Version:    8022
  UID:                 6f9e8107-5784-4f34-935c-924a415d0b38
Spec:
  Gateway Class Name:  consul-api-gateway
  Listeners:
    Allowed Routes:
      Namespaces:
        From:  Same
    Name:      https
    Port:      8443
    Protocol:  HTTPS
    Tls:
      Certificate Refs:
        Group:
        Kind:   Secret
        Name:   consul-server-cert
      Mode:     Terminate
Status:
  Conditions:
    Last Transition Time:  1970-01-01T00:00:00Z
    Message:               Waiting for controller
    Reason:                NotReconciled
    Status:                Unknown
    Type:                  Accepted
Events:                    <none>
```

```
kubectl apply --filename api-gw/consul-api-gateway.yaml --namespace consul && \
kubectl wait --for=condition=accepted gateway/api-gateway --namespace consul --timeout=90s && \
kubectl apply --filename api-gw/routes.yaml --namespace consul && \
kubectl apply --filename api-gw/intentions.yaml --namespace consul

gateway.gateway.networking.k8s.io/api-gateway configured
error: timed out waiting for the condition on gateways/api-gateway
```
```
❯ ls -1 api-gw
consul-api-gateway.yaml
routes.yaml
```

**Comment by mkurcius** [comment]
Update `self-managed/local/api-gw/consul-api-gateway.yaml` with content from the page:
https://developer.hashicorp.com/consul/tutorials/get-started-kubernetes/kubernetes-gs-ingress#review-consul-api-gateway-configuration-4

```
---
apiVersion: gateway.networking.k8s.io/v1beta1
# The Gateway is the main infrastructure resource that links API gateway components.
kind: Gateway
metadata:
  name: api-gateway
  namespace: consul
spec:
  gatewayClassName: consul
  # Configures the listener that is bound to the gateway's address.
  listeners:
    # Defines the listener protocol (HTTP, HTTPS, or TCP)
    - protocol: HTTPS
      port: 8443
      name: https
      allowedRoutes:
        namespaces:
          from: Same
      tls:
        # Defines the certificate to use for the HTTPS listener.
        certificateRefs:
          - name: consul-server-cert
```

there are minor changes like indents in `listeners` section

after file is updated, conditions are met
